### ISSUE TITLE
Repository does not exist

### ISSUE THREAD

**Issue by michalkania** [sudoforge/docker-images#86]
> docker: Error response from daemon: pull access denied for sudoforge/murmur, repository does not exist or may require 'docker login'.

Well, it's true because if you try to go to the docker's murmur repository it'll 404 in your face.

Will you create the repository again?

**Comment by sudoforge** [comment]
@michalkania - sorry for not getting back to you sooner, I was out of commission during the holidays and now due to laser eye surgery.

I'm in the process of reworking this repository and have quite a few changes coming. The murmurd image will be available from the public docker registry at `sudoforge/murmurd` by this weekend (note the addition of the `d`). References in this repository will be updated when this has been completed. 

I'm reopening this so you can more easily track when I've got it up and running. In the meantime, you can simple grab the dockerfile and build it yourself with the expected tag so that pulling updates from my user's register image works seamlessly for you in the future:


```
$ docker build -t sudodorge/murmurd
```

Please let me know if you need anything else.

**Comment by michalkania** [comment]
TY for feedback. I've built it already, but I just like the effectivness of having things in a repository and I used this one in the past so I'm glad it's coming back :)

**Comment by michalkania** [comment]
TY for feedback. I've built it already, but I just like the effectivness of having things in a repository and I used this one in the past so I'm glad it's coming back :)

**Comment by sudoforge** [comment]
Deleted a duplicate comment.

**Comment by sudoforge** [comment]
This has been available since Mar 29 2019 at approximately 14:00 PDT.

https://hub.docker.com/r/sudoforge/murmurd

The repository metadata is lacking, and I have yet to set up an autopush pipeline, but those will come in the next few weeks, as my free time allows.

To pull the latest successful build (at the present moment, this is version `1.2.19`):

```
$ docker pull sudoforge/murmurd:latest
```
